TRUNCATE TABLE units2morphs CASCADE;
TRUNCATE TABLE morph2glosses CASCADE;
TRUNCATE TABLE expressions2units CASCADE;
TRUNCATE TABLE expressions CASCADE;
TRUNCATE TABLE glosses CASCADE;
TRUNCATE TABLE morphs CASCADE;
TRUNCATE TABLE units CASCADE;
TRUNCATE TABLE langs CASCADE;